### ISSUE TITLE
Huobi, Bitcurex, LakeBTC, Bitcoinde failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [andrefbsantos/libdynticker#4]
Results :

Failed tests:   testParseJson(mobi.boilr.libdynticker.exchanges.HuobiExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcurexExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.LakeBTCExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcoindeExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 232, Failures: 4, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Just testing.
