### ISSUE TITLE
Bitspark, Bitspark, CryptoFacilities, Allcoin, Bitcurex, Bitcoinde failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [andrefbsantos/libdynticker#5]
Results :

Failed tests:   testGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitsparkExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CryptoFacilitiesExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.AllcoinExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcurexExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcoindeExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 240, Failures: 6, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Duplicated of #4.
