### ISSUE TITLE
CCEDK, Bitcoinde failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [andrefbsantos/libdynticker#6]
Results :

Failed tests:   testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CCEDKExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.BitcoindeExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 240, Failures: 2, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Fixed in 404007ced461bcdad91b9808c0e7c725157981e0.
