### ISSUE TITLE
CCEDK, CCEDK, NXTAsset, Bit2C failed automatic tests

### ISSUE THREAD

**Issue by fluffylittlecubie** [andrefbsantos/libdynticker#9]
Results :

Failed tests:   testGetPairs(mobi.boilr.libdynticker.exchanges.CCEDKExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.CCEDKExchangeTest)
  testGetPairs(mobi.boilr.libdynticker.exchanges.NXTAssetExchangeTest)
  testGetLastValueWithPairsFromGetPairs(mobi.boilr.libdynticker.exchanges.Bit2CExchangeTest)

Tests in error: 
  testSecondGetPairsFromAPIDoesActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): tried to access class org.mockito.internal.creation.cglib.CGLIBHacker from class org.mockito.internal.creation.MethodInterceptorFilter
  testSecondGetPairsFromAPIDoesntActive(mobi.boilr.libdynticker.core.GetPairsFromAPITest): org/mockito/internal/creation/cglib/CGLIBHacker

Tests run: 284, Failures: 4, Errors: 2, Skipped: 1

**Comment by andrefbsantos** [comment]
Retested and everything is fine.
